### ISSUE TITLE
Unable to boot usb from Ubuntu Xenial (16.04)

### ISSUE THREAD

**Issue by danjde** [unetbootin/unetbootin#98] opened 2017-01-02 15:59 UTC
Hi Staff,
I've try to transfer (from a installed Xenial Ubuntu Linux) a Xenial iso (Gnome alternate and official Xenial) to usb using unetbootin 625-1~xenial1, obtain this message:
This is not a bootable disk. Please insert a bootable....

I've try to reformat the pen drive with the same issue. I've try to change usb key, with the same issue.

have you tryed unetbootin with Xenial?

Many thanks

**Comment by gkovacs** [comment] 2017-04-23 23:19
seems to be the same issue as https://github.com/unetbootin/unetbootin/issues/112 have just reproduced and fixed it (was because the command line options for sfdisk have changed in ubuntu), will be in the following release (coming out this week)

**Comment by gkovacs** [comment] 2017-04-24 08:33
Now fixed in the 638 release.

**Closed by gkovacs** 2017-04-24 08:33 UTC
