### ISSUE TITLE
unetbootin does not work on macOS Catalina

### ISSUE THREAD

**Issue by AaronGillBraun** [unetbootin/unetbootin#236] opened 2019-10-06 03:27 UTC
This is not a duplicate of the other issues that have been closed, because the most recent release still does not work on the latest macOS Catalina beta. When launching the app, it goes unresponsive  and then hangs forever. After checking the console, it seems that unetbootin produced the following error twice while launching:
```
Failed to set up CFPasteboardRef 'ApplePerContextInputPasteboard'. Error: <error: 0x7fffa4786e30> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x7fffa4786f98> { length = 18, contents = "Connection invalid" }
}
```
Another log message, also from unetbootin was in the console, but it wasn't marked with the `error` type,  but it might be important:
```
LSExceptions shared instance invalidated for timeout.
```

What could be causing this?

**Comment by gkovacs** [comment] 2019-10-08 19:43
thanks for the bug report! I had expected catalina's only breaking change was dropping 32-bit support, it seems they broke more things and additional changes will be required to support it. I don't have access to my development mac these 2 weeks, I'll investigate this issue as soon as I do

**Comment by gkovacs** [comment] 2019-10-14 15:36
the app is already 64-bit, whatever issue is causing it not to work in catalina isn't them breaking 32-bit support but something else. I'll investigate once I have access to a mac that I can upgrade to catalina (2 weeks from now).

**Comment by KyleJSaunders** [comment] 2019-10-22 03:51
I came across a similar issue. Attached I'll post my crash report to help with your diagnosis. @gkovacs 

[unetbootin_2019-10-21-213649_Kyles-MacBook-Pro.crash.zip](https://github.com/unetbootin/unetbootin/files/3753777/unetbootin_2019-10-21-213649_Kyles-MacBook-Pro.crash.zip)

**Comment by harryrford** [comment] 2019-10-24 10:56
Can confirm I'm having the same issue, the latest version of Unetbootin opens but fails to build as shown in the screenshot. I am running macOS 10.15 Catalina.

I thought I would mention that I have been having serious issues trying to get my Mac to recognise external devices to boot into. I have the suspicion **Catalina put restrictions to disk formatting and even blocked booting from external devices.** Similar software to Unetbootin such as Etcher fails to format and write to external devices even with my device pre-formatted using FAT32 and GUID partition map. If anyone can confirm similar behaviour It would be interesting to know.

**Comment by mv-go** [comment] 2019-10-24 15:07
> Can confirm I'm having the same issue, the latest version of Unetbootin opens but fails to build as shown in the screenshot. I am running macOS 10.15 Catalina.
> 
> I thought I would mention that I have been having serious issues trying to get my Mac to recognise external devices to boot into. I have the suspicion **Catalina put restrictions to disk formatting and even blocked booting from external devices.** Similar software to Unetbootin such as Etcher fails to format and write to external devices even with my device pre-formatted using FAT32 and GUID partition map. If anyone can confirm similar behaviour It would be interesting to know.

Can confirm both the original issue here and the external drive formatting errors, mentioned above.

**Comment by BryanWall** [comment] 2019-10-24 17:31
Other USB flashing apps are having issues also. It seems to be a permissions issue with Balena Etcher, so maybe that's the issue with Unetbootin, also. To get Etcher to work, you have to start it with sudo from terminal. Here's a link to their issue thread that might shed some light on the issue here.

https://github.com/balena-io/etcher/issues/2833

**Comment by mawesome4ever** [comment] 2019-10-25 18:16
Found a workaround! Open Terminal and a Finder window, then on the Finder window navigate to the Application folder, locate UNetbootin, Right-Click on the application and choose Show Package Contents, click on the drop-down folder with the name "MacOS", now go over to the Terminal window and type "sudo " (don't forget the space), then drag over the executable over to terminal and hit enter on the terminal window. After that, it should start-up!

**Comment by terraboss** [comment] 2019-10-25 18:42
Nice @mawesome4ever 

I can confirm this workaround. But it seems, another prompt requires additional privileges 

<img width="555" alt="Bildschirmfoto 2019-10-25 um 20 39 57" src="https://user-images.githubusercontent.com/69455/67595897-e78d4c80-f767-11e9-9290-40b3994bf335.png">
<img width="870" alt="Bildschirmfoto 2019-10-25 um 20 38 34" src="https://user-images.githubusercontent.com/69455/67595899-e825e300-f767-11e9-9970-b92654616dc3.png">

**Comment by sam0x17** [comment] 2019-10-26 16:23
using sudo trick worked for me. Definitely a permissions issue

**Comment by P4nd3m1c** [comment] 2019-10-27 21:52
Sudo Trick worked for me, too.
Thanks for that!

**Comment by DeusExTaco** [comment] 2019-10-27 22:54
Sudo worked...thanks!

**Comment by Juleship** [comment] 2019-10-31 19:36
This is not closed and running an app with sudo is a bad idea :/

**Comment by Laim** [comment] 2019-11-08 22:40
Is there any updates on the potential fix for this?  Been driving my insane the last few hours and just found this. :|

**Comment by WilldelaVega777** [comment] 2019-11-11 18:23
![UnetBootIn Not Working](https://user-images.githubusercontent.com/3942218/68610748-16046a80-047e-11ea-9ed0-c1262654d9a4.png)

**Comment by LW-Ho** [comment] 2019-11-12 11:32
> Nice @mawesome4ever
> 
> I can confirm this workaround. But it seems, another prompt requires additional privileges
> 
> <img alt="Bildschirmfoto 2019-10-25 um 20 39 57" width="555" src="https://user-images.githubusercontent.com/69455/67595897-e78d4c80-f767-11e9-9290-40b3994bf335.png">
> 
> <img alt="Bildschirmfoto 2019-10-25 um 20 38 34" width="870" src="https://user-images.githubusercontent.com/69455/67595899-e825e300-f767-11e9-9970-b92654616dc3.png">

Thanks a lot, can working.

**Comment by RetroSoftwareRepository** [comment] 2020-01-10 02:10
I also have this issue as I use this tool to make bootable Windows USB drives for use with other computers. BalenaEtcher can't do that despite working properly under it.

**Comment by terraboss** [comment] 2020-01-10 07:56
It seems, there is no priority on this :-(

**Comment by floyernick** [comment] 2020-01-13 13:14
How did you check the console? Where did you find the log of app?

**Comment by gkovacs** [comment] 2020-01-21 10:50
catalina should now work correctly with release 377, please report issues if you still encounter them

**Closed by gkovacs** 2020-01-21 10:50 UTC

**Comment by Samm786** [comment] 2020-10-19 08:41
UNetbootin does not use distribution-specific rules to make bootable USB drives, most Linux ISO files should be loaded correctly with UNetbootin or other tool like [rufus](https://rufus.ie/), [wonderiso](https://www.sysgeeker.com/iso-burner.html).

but,  not all distributions can be boot from USB, and some other distributions require additional boot options or modifications in order to boot from a USB drive, so these ISO files will not work as they are. In addition, different system ISO files have different startup mechanisms, so don't expect them to work normally every time.

what's more, I suggest you to try rufus or wonderiso tool to create a bootable USB on your macOS.

**Comment by Samm786** [comment] 2020-10-19 10:34
It sounds like your USB flash drive is not recognized as being bootable?

Try using UNetbootin (http://unetbootin.sourceforge.net/). It should make your USB flash drive bootable.

Download the the version for Mac OS X and simply run it. Follow the prompts and select your USB flash drive, ISO file, or have it download the latest ISO for you. I've used UNetbootin several times under OS X for various Linux distros and it's always worked well.

**Comment by romulus-ai** [comment] 2021-01-10 10:44
Same happens in OSX Big Sur again and the Workaround from Catalina is not working anymore. The OSAScript Permission comes up and after that nothing happens anymore. However, starting the wool from Terminal with the command "sudo /Applications/unetbootin.app/Contents/MacOS/unetbootin rootcheck=yes" works! With "rootcheck=no" it is not working!

**Comment by sam0x17** [comment] 2021-01-12 05:18
Someone should make a new issue for Big Sur

**Comment by Glench** [comment] 2021-03-16 14:36
It's still hanging for me on unetbootin 702 on Catalina (10.15.7). Running from the command line with sudo doesn't work. Any ideas?

**Comment by Stasyanz** [comment] 2023-01-09 19:04
Pressing Ok button doesn't start the burning process
